Traceback (most recent call last):
  File "c:\Users\Andre\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Users\Andre\anaconda3\envs\env_taller_concurrency\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/Users/Andre/anaconda3/Scripts/conda.exe', 'activate']' returned non-zero exit status 1.
